name: Python Tests

on:
  pull_request:

jobs:
  test:
    runs-on: qe-ubuntu20

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.uv.txt
          uv pip compile requirements.uv.txt

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          sh bin/run-tests.sh
